---
title: "Zeisel Week 2"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE,autodep=TRUE, cache.comments=TRUE)
```

Column sum and sparsity
===

```{r, echo = F}
rm(list=ls())
load("../../SOUP/data/zeisel.rda")

dat <- zeisel$counts
dat <- t(apply(dat, 1, function(x){x/sum(x)}))
dat <- 1000*log(dat + 1)
```


```{r}
sparsity_vec <- apply(dat, 2, function(x){
  length(which(x!=0))
})

sum_vec <- colSums(dat)
```

```{r}
quantile_sum <- quantile(sum_vec, prob = 0.95)
plot(sparsity_vec, sum_vec, ylim = c(0, quantile_sum), col = rgb(0,0,0,0.1), pch = 16)
```

```{r}
idx <- which(sum_vec <= quantile_sum)
dat <- dat[,idx]

sparsity_vec <- apply(dat, 2, function(x){
  length(which(x!=0))
})
sum_vec <- colSums(dat)
```

Column ANOVA
===

```{r, echo = F}
anova_func <- function(x){
  uniq <- unique(zeisel$cell.info[,2])
  k <- length(uniq)
  n <- length(x)

  between <- sum(sapply(uniq, function(k){
    idx <- which(zeisel$cell.info[,2] == k)
    length(idx)*(mean(x[idx]) - mean(x))^2
  }))/(k-1)

  within <- sum(sapply(unique(zeisel$cell.info[,2]), function(k){
    idx <- which(zeisel$cell.info[,2] == k)
    sum((x[idx]-mean(x[idx]))^2)
  }))/(n-k)

  between/within
}

anova_vec <- apply(dat, 2, anova_func)
plot(sort(anova_vec))
```


Largest

```{r, echo = F}
par(mfrow = c(2,2))
cell_idx <- as.numeric(as.factor(zeisel$cell.info[,2]))
idx <- order(anova_vec, decreasing = T)[1:4]
for(i in 1:4){
  plot(jitter(sort(dat[,idx[i]])), col = c(1:7)[cell_idx[order(dat[,idx[i]])]])
}
```

Smallest

```{r, echo = F}
par(mfrow = c(2,2))
cell_idx <- as.numeric(as.factor(zeisel$cell.info[,2]))
idx <- order(anova_vec, decreasing = F)[1:4]
for(i in 1:4){
  plot(jitter(sort(dat[,idx[i]])), col = c(1:7)[cell_idx[order(dat[,idx[i]])]])
}
```

Medium

```{r, echo = F}
par(mfrow = c(2,2))
cell_idx <- as.numeric(as.factor(zeisel$cell.info[,2]))
mid <- floor(length(anova_vec)/2)
idx <- order(anova_vec, decreasing = F)[mid:(mid+4)]
for(i in 1:4){
  plot(jitter(sort(dat[,idx[i]])), col = c(1:7)[cell_idx[order(dat[,idx[i]])]])
}
```


```{r, echo = F}
stopifnot(length(anova_vec) == length(sparsity_vec))

idx <- order(anova_vec, decreasing = T)[1:700]
col_vec <- rep(rgb(0,0,0,0.1), length(sparsity_vec))
col_vec[idx] <- rgb(1,0,0,0.5)
pch_vec <- rep(1, length(sparsity_vec))
pch_vec[idx] <- 16
plot(sparsity_vec, sum_vec, ylim = c(0, quantile_sum),
     col = col_vec, pch = pch_vec)

```

```{r, echo = F}
dat2 <- dat[,idx]
res_svd <- svd(dat2)
```

Singular values

```{r, echo = F}
plot(sort(res_svd$d, decreasing = T)[1:50], pch = 16)
```

Left eigenvectors (Cells)

```{r, echo = F}
plot(res_svd$u[,1], res_svd$u[,2], pch = 16, col = rgb(0.1, 0.1, 0.1, 0.25),
     xlim = range(c(res_svd$u[,1], 0)), ylim = range(c(res_svd$u[,2], 0)))

lines(c(-10,10), rep(0,2), col = "red", lwd = 2)
lines(rep(0,2), c(-10,10), col = "red", lwd = 2)
```

```{r}
plot(res_svd$u[,1], res_svd$u[,2], pch = 16, col = rgb(0.1, 0.1, 0.1, 0.25), xlim = c(-0.025, -0.01), ylim = c(-0.02, 0.02))
```

By cells 

```{r, echo = F, fig.height = 7}
par(mfrow = c(3,3))
xrange <- range(res_svd$u[,1])
yrange <- range(res_svd$u[,2])
uniq <- unique(zeisel$cell.info[,2])
for(i in 1:7){
  idx <- which(zeisel$cell.info[,2] == uniq[i])
  plot(res_svd$u[idx,1], res_svd$u[idx,2], pch = 16, main = uniq[i],
       xlim = xrange, ylim = yrange, xlab = "U[,1]", ylab = "U[,2]")
  lines(c(-10,10), rep(0, 2), col = "red", lwd = 2)
  lines(rep(0, 2), c(-10,10), col = "red", lwd = 2)
}
```

Right eigenvectors (Genes)

```{r, echo = F}
plot(res_svd$v[,1], res_svd$v[,2], pch = 16, col = rgb(0.1, 0.1, 0.1, 0.25),
     xlim = range(c(res_svd$v[,1], 0)), ylim = range(c(res_svd$v[,2], 0)))

lines(c(-10,10), rep(0,2), col = "red", lwd = 2)
lines(rep(0,2), c(-10,10), col = "red", lwd = 2)
```

```{r}
plot(res_svd$u[,1], res_svd$u[,2], pch = 16, col = rgb(0.1, 0.1, 0.1, 0.25), xlim = c(-0.025, -0.01), ylim = c(-0.025, 0.025))
```


```{r}
rank <- 8
dat_approx <- res_svd$u[,1:rank] %*% diag(res_svd$d[1:rank]) %*% t(res_svd$v[,1:rank])
residual <- dat2 - dat_approx

set.seed(10)
idx <- sample(prod(dim(dat)), 5e5)

par(mfrow = c(1,2))
plot(as.numeric(dat_approx)[idx], as.numeric(dat2)[idx], col = rgb(0,0,0,0.1), pch = 16, asp = T)
mean_val <- seq(0, 10, length.out = 1000)
lines(mean_val, mean_val, col = "red", lwd = 2)
sd_top <- mean_val + mean_val
sd_bot <- mean_val - mean_val
lines(mean_val, sd_top, col = "red", lwd = 2, lty = 2)
lines(mean_val, sd_bot, col = "red", lwd = 2, lty = 2)

plot(as.numeric(dat_approx)[idx], as.numeric(dat2)[idx], col = rgb(0,0,0,0.1), pch = 16, xlim = c(0,3),
     ylim = c(0, 3), asp = T)
mean_val <- seq(0, 10, length.out = 1000)
lines(mean_val, mean_val, col = "red", lwd = 2)
sd_top <- mean_val + mean_val
sd_bot <- mean_val - mean_val
lines(mean_val, sd_top, col = "red", lwd = 2, lty = 2)
lines(mean_val, sd_bot, col = "red", lwd = 2, lty = 2)
```

```{r}
rank <- 8
dat_approx <- res_svd$u[,1:rank] %*% diag(res_svd$d[1:rank]) %*% t(res_svd$v[,1:rank])/log(2)
residual <- dat2 - dat_approx

set.seed(10)
idx <- sample(prod(dim(dat)), 5e5)

par(mfrow = c(1,2))
plot(as.numeric(dat_approx)[idx], as.numeric(dat2)[idx], col = rgb(0,0,0,0.1), pch = 16, asp = T)
mean_val <- seq(0, 10, length.out = 1000)
lines(mean_val, mean_val, col = "red", lwd = 2)
sd_top <- mean_val + mean_val
sd_bot <- mean_val - mean_val
lines(mean_val, sd_top, col = "red", lwd = 2, lty = 2)
lines(mean_val, sd_bot, col = "red", lwd = 2, lty = 2)

plot(as.numeric(dat_approx)[idx], as.numeric(dat2)[idx], col = rgb(0,0,0,0.1), pch = 16, xlim = c(0,3),
     ylim = c(0, 3), asp = T)
mean_val <- seq(0, 10, length.out = 1000)
lines(mean_val, mean_val, col = "red", lwd = 2)
sd_top <- mean_val + mean_val
sd_bot <- mean_val - mean_val
lines(mean_val, sd_top, col = "red", lwd = 2, lty = 2)
lines(mean_val, sd_bot, col = "red", lwd = 2, lty = 2)
```
